2022-10-08 13:34:06,014 (7feca1999808) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 819d367 (Fri Sep 23 01:15:17 UTC 2022)
2022-10-08 13:34:06,014 (7feca1999808) :  DEBUG (core:361) - Using the elevated policy
2022-10-08 13:34:06,015 (7feca1999808) :  DEBUG (core:450) - Starting runtime component.
2022-10-08 13:34:06,016 (7feca1999808) :  DEBUG (core:450) - Starting caching component.
2022-10-08 13:34:06,016 (7feca1999808) :  DEBUG (core:450) - Starting data component.
2022-10-08 13:34:06,016 (7feca1999808) :  DEBUG (core:450) - Starting networking component.
2022-10-08 13:34:06,017 (7feca1999808) :  DEBUG (networking:265) - No cookie jar found
2022-10-08 13:34:06,017 (7feca1999808) :  DEBUG (networking:428) - Setting the default network timeout to 20.0
2022-10-08 13:34:06,018 (7feca1999808) :  DEBUG (core:450) - Starting localization component.
2022-10-08 13:34:06,018 (7feca1999808) :  INFO (localization:409) - Setting the default locale to en-us
2022-10-08 13:34:06,018 (7feca1999808) :  DEBUG (core:450) - Starting messaging component.
2022-10-08 13:34:06,019 (7feca1999808) :  DEBUG (core:450) - Starting debugging component.
2022-10-08 13:34:06,019 (7feca1999808) :  DEBUG (core:450) - Starting services component.
2022-10-08 13:34:06,019 (7feca1999808) :  DEBUG (core:450) - Starting myplex component.
2022-10-08 13:34:06,020 (7fec9e7dbb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.thetvdb'
2022-10-08 13:34:06,020 (7feca1999808) :  DEBUG (core:450) - Starting notifications component.
2022-10-08 13:34:06,151 (7feca1999808) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2022-10-08 13:34:06,155 (7feca1999808) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2022-10-08 13:34:06,160 (7feca1999808) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2022-10-08 13:34:06,162 (7feca1999808) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 242, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 220, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 158, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2022-10-08 13:34:06,169 (7feca1999808) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2022-10-08 13:34:06,170 (7fec9e5a2b38) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2022-10-08 13:34:06,171 (7feca1999808) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2022-10-08 13:34:06,171 (7fec9e5a2b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2022-10-08 13:34:06,171 (7fec9e55cb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400'
2022-10-08 13:34:06,172 (7feca1999808) :  DEBUG (core:150) - Finished starting framework core
2022-10-08 13:34:06,172 (7feca1999808) :  DEBUG (core:560) - Loading plug-in code
2022-10-08 13:34:06,286 (7fec9e5a2b38) :  DEBUG (services:362) - Loaded services
2022-10-08 13:34:06,290 (7fec9e55cb38) :  DEBUG (core:538) - Machine identifier is 3009cb45a0c80e74ee90000b6226514228f9c608
2022-10-08 13:34:06,298 (7fec9e55cb38) :  DEBUG (core:539) - Server version is 1.29.0.6244-819d3678c
2022-10-08 13:34:06,304 (7fec9e57fb38) :  DEBUG (services:438) - No shared code to load
2022-10-08 13:34:06,588 (7feca1999808) :  DEBUG (core:566) - Finished loading plug-in code
2022-10-08 13:34:06,589 (7feca1999808) :  DEBUG (agentkit:1132) - Creating new agent class called TVDBAgent
2022-10-08 13:34:06,589 (7feca1999808) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}]
2022-10-08 13:34:06,590 (7feca1999808) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__'
2022-10-08 13:34:25,384 (7feca1999808) :  INFO (core:611) - Started plug-in
2022-10-08 13:34:25,384 (7feca1999808) :  DEBUG (socketinterface:160) - Starting socket server
2022-10-08 13:34:25,385 (7feca1999808) :  DEBUG (runtime:1117) - Created a thread named 'start'
2022-10-08 13:34:25,385 (7feca1999808) :  INFO (socketinterface:184) - Socket server started on port 38949
2022-10-08 13:34:25,386 (7feca1999808) :  INFO (pipeinterface:25) - Entering run loop
2022-10-08 13:34:25,386 (7feca1999808) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2022-10-08 13:34:25,387 (7feca1999808) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2022-10-08 13:34:25,388 (7feca1999808) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 151 bytes
2022-10-08 13:34:25,390 (7fec9e32db38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2022-10-08 13:34:25,397 (7fec9da9fb38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2022-10-08 13:34:25,414 (7fec9e32db38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2022-10-08 13:34:25,415 (7fec9e32db38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2022-10-08 13:34:25,416 (7fec9da9fb38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2022-10-08 13:34:25,417 (7fec9e32db38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2022-10-08 13:34:25,417 (7fec9da9fb38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2022-10-08 13:34:25,417 (7fec9e32db38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
2022-10-08 13:34:25,418 (7fec9da9fb38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2022-10-08 13:34:25,419 (7fec9da9fb38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
